config/routes.rb
Rails.application.routes.draw do
  get 'todo/index'
  resources :todo_lists
  root 'todo#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  validates :title, presence: true,
                   length: { minimum: 5 , maximum:20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @todo_lists=TodoList.all
  end
  def new
    @todo_list=TodoList.new
  end

  def edit
    @todo_list=TodoList.find(params[:id])
  end

  def create
     # render plain: params[:todo_list].inspect
     @todo_list=TodoList.new(todo_list_params)
     if @todo_list.save
       redirect_to @todo_list
     else
       render 'new'
     end
  end


  def update
  @todo_list = TodoList.find(params[:id])
  if @todo_list.update(todo_list_params)
    redirect_to @todo_list
  else
    render 'edit'
  end
  end

  def show
    @todo_list=TodoList.find(params[:id])
  end

  def destroy
  @todo_list = TodoList.find(params[:id])
  @todo_list.destroy
  redirect_to todo_lists_path
  end

  private
  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoWith</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/index.html.erb
<!-- <h1>Yahoo! This is my first rails app</h1>
<h2>👏👏👏👏👏👏👏👏👏👏</h2>
<h3>This is self motivation</h3>
<h4>Congrats veera you will learn more</h4> -->

<h1>This is homepage for todos website</h1>
<%= link_to 'Todos', controller: 'todo_lists' %>

app/views/todo_lists/_form.html.erb
<%= form_with model: @todo_list, local: true do |form| %>

  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo_list.errors.count, "error") %> prohibited
        this todo_list from being saved:
      </h2>
      <ul>
        <% @todo_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/todo_lists/edit.html.erb
<h1>Edit Todo List</h1>

<%= render 'form' %>
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing Todos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @todo_lists.each do |todo_list| %>
    <tr>
      <td><%= todo_list.title %></td>
      <td><%= todo_list.description %></td>
      <td><%= link_to 'Show', todo_list_path(todo_list) %></td>
      <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
      <td><%= link_to 'Delete', todo_list_path(todo_list),
            method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Home ',root_path %>
<%= link_to 'New List ',new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New List</h1>
<%= render 'form' %>

app/views/todo_lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Home ',root_path %>
<%= link_to 'Back ',todo_lists_path %>